### ISSUE TITLE
Killed, but not helped...

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_unk#1]
It may happen that the unknown after the murder will not be revived, this happened to me when the spy killed the unknown.

**Comment by TimGoll** [comment]
I can't confirm this. I just tested this and the spy was revived as a traitor (which confused the tbh). But he was revived.

**Comment by dok441** [comment]
Well I man said, I have the logs open and he was revived and died and all.

**Comment by TimGoll** [comment]
you said that he wasn't revived and now you say he was revived?

**Comment by dok441** [comment]
He was revived, a translation error apparently.

**Comment by TimGoll** [comment]
okay and what is the problem? The unknown should be revived. This is the point of this role.

**Comment by dok441** [comment]
So that's the problem, he was killed by a spy, and he didn't resurrect, he didn't resurrect...

**Comment by TimGoll** [comment]
okay so we're back to my first comment. I can't reporduce it, it works for me. Maybe it is connected to the same problem that your marker has since it seems like some hits aren't registered correctly on your server.

Sidenote: The revival only works when the killer is not the world. If you use a weapon like the friendship beam, the unknown will not be revived

**Comment by dok441** [comment]
The weapon was used as a shotgun.
